site_name: CM5 Flash JIG
site_url: https://everypinio.github.io/cm5-flash-jig
theme:
  name: material
  font:
    text: Golos Text
  features:
      - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: purple
      accent: deep-purple
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: purple
      accent: deep-purple
      scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: purple
      accent: deep-purple
      scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: !ENV DISCORD_FEEDBACK_NOTE

  social:
    - icon: fontawesome/brands/discord
      link: !ENV LINK_DISCORD
      name: Everypin on Discord

    - icon: fontawesome/brands/github
      link: !ENV LINK_GITHUB
      name: Everypin on GitHub

    - icon: fontawesome/brands/linkedin
      link: !ENV LINK_LINKEDIN
      name: Everypin on LinkedIn

    - icon: fontawesome/solid/at
      link: !ENV LINK_EMAIL
      name: Send us an email

copyright: !ENV COPYRIGHT_NOTE

plugins:
  # the built site fails to display the search bar without the 'offline' plugin
  - offline
