[pytest]

testpaths = tests
python_files = test_*.py
norecursedirs = assets data lib .pytest_cache

; Warning: Configuring HardPy usage here restricts execution to 'pytest' with HardPy enabled.
; For more flexibility, consider running tests via the command line: `pytest --hardpy-pt`
;
; The default database URL is `http://dev:dev@localhost:5984/`.
; This does not need to be explicitly set unless you intend to change it.

; addopts = --hardpy-pt
;           --hardpy-db-url http://dev:dev@localhost:5984/

markers =
    module_name(name): HardPy module display name
    case_name(name): HardPy case display name
    critical: HardPy critical test/module; failure or skip stops subsequent tests
    hold_power_for_module: Power Management; disables per-test power cutoff safety net
