[pytest]
testpaths = .
python_files = test_*.py
pythonpath = ../..

markers =
	module_name(name): HardPy module display name
	case_name(name): HardPy case display name
	critical: HardPy critical test/module; failure or skip stops subsequent tests
