name: Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean
        env:
          GOOGLE_ANALYTICS_KEY: ${{ vars.GOOGLE_ANALYTICS_KEY }}
          DISCORD_FEEDBACK_NOTE: ${{ vars.DISCORD_FEEDBACK_NOTE }}
          LINK_DISCORD: ${{ vars.LINK_DISCORD }}
          LINK_GITHUB: ${{ vars.LINK_GITHUB }}
          LINK_LINKEDIN: ${{ vars.LINK_LINKEDIN }}
          LINK_EMAIL: ${{ vars.LINK_EMAIL }}
          COPYRIGHT_NOTE: ${{ vars.COPYRIGHT_NOTE }}
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - uses: actions/deploy-pages@v5
        id: deployment
